# Generated by Django 3.2.5 on 2022-02-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_configurations', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='food_entry_limit',
            field=models.IntegerField(default=3, verbose_name='Food entry limit per meal'),
        ),
    ]
